# Generated by Django 4.0.3 on 2022-03-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assign',
            new_name='Assignment',
        ),
    ]
