# Generated by Django 4.0.3 on 2022-03-06 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_assignment_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='submitted_inst',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
