# Generated by Django 4.0.3 on 2022-03-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studentassignment_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cohort'),
        ),
    ]
