# Generated by Django 4.0.3 on 2022-03-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_is_public_studentassignment_submitted_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
