# Generated by Django 4.0.3 on 2022-03-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cohort_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='current',
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cohort')),
            ],
        ),
    ]
