# Generated by Django 4.0.3 on 2022-03-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_assignment_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='test',
        ),
    ]
